name: rune
description: A DSL for scripting Sega PSIV assembly cutscenes.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fast_immutable_collections: ^9.1.1
  charcode: ^1.2.0
  characters: ^1.1.0
  collection: ^1.15.0
  quiver: ^3.0.1
  logging: ^1.0.2
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.3
  js: ^0.6.3
  google_apps:
    git: https://github.com/alechenninger/dart_google_apps.git
