name: rune
description: A DSL for scripting Sega PSIV disassembly cutscenes.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  charcode: ^1.2.0
  characters: ^1.1.0
  collection: ^1.15.0
  quiver: ^3.0.1
  logger: ^1.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.3
  js: ^0.6.3
  google_apps: ^0.1.2
